services:
  ateliermecanique:
    build: ./ateliermecanique-ws
    hostname: ateliermecanique
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql1:3306/ateliermecanique-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd
      SPRING_PROFILES_ACTIVE: docker


    depends_on:
      mysql1:
        condition: service_healthy
    networks:
      - app-network


  mysql1:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=ateliermecanique-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql1:/var/lib/mysql1
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  frontend:
    build:
      context: ./acms-react-app
      dockerfile: Dockerfile
    volumes:
      - ./acms-react-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
    driver: bridge
